### ISSUE TITLE
Desenvolver modal para visualizar o contato do locatário

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#101]
Exemplo figma, deve ser melhorado, e pesquisar algum exemplo melhor para aplicação!

![Image](https://github.com/DevsDomain/Bike4you/assets/104475381/e13d06e8-13d6-4587-b9c6-7d5ad8e77a65)

**Comment by itsmorais** [comment]
Componente criado, porém falta a funcionalidade, fazer ele aparecer na tela @fnddavi trabalhando nisso

**Comment by itsmorais** [comment]
![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/c7409443-29fd-498f-9964-df774b18a9e5)
