### ISSUE TITLE
Desenvolver Componente GERAL

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#107]

**Comment by Claudia-Nunes** [comment]
![Image](https://github.com/DevsDomain/Bike4you/assets/104475381/fffec700-04e9-4b0e-bf7a-8d0fe690acf5)

**Comment by Jummanso** [comment]
Início atividade

**Comment by Jummanso** [comment]
Feito layout:

![image](https://github.com/DevsDomain/Bike4you/assets/126696706/4f9e3f64-2511-4914-9148-7db4a099c887)

**Comment by Jummanso** [comment]
Iniciando estudo para integrar dados na tabela

**Comment by Jummanso** [comment]
Feita a integração com banco de dados e teste de aumento automático da página, @itsmorais faltando apenas barra de rolamento caso a pessoa cadastre mais de 6 bicicletas.

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/88d0b123-3119-4ba9-99e3-325b649bd7d0)
