### ISSUE TITLE
Criar Função no BD para componente Avaliação

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#108]
Conectar Banco de Dados com o componente de Avaliação,
@itsmorais  acompanhar a @fnddavi  para conectividade das tarefas

**Comment by itsmorais** [comment]
Testar endpoint = http://localhost:3026/rent/rate?idBike=8
substituir o n° 8 pelo ID de uma bike existente em seu banco de dados
obs: Se essa bike não tiver avaliações a nota será 0 por padrão


![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/f8d7835c-7280-4465-9ccf-4490d3b90e7e)
