### ISSUE TITLE
Criar função no BD para Pagina GERAL

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#109]
Esta tarefa depende da #107 ficar concluida

Conectar Banco de Dados com o componente de Avaliação,
@itsmorais  acompanhar a @Jummanso  para conectividade das tarefas

**Comment by itsmorais** [comment]
Conforme alinhado, dados a serem puxados do banco são:
cod_bike, nome bike, status(disponivel,alugada,pendente), avaliação

**Comment by itsmorais** [comment]
Funções criadas no banco de dados, método GET via typeORM criado com sucesso!

FUNÇÃO PARA UTILIZAR NO FRONT-END QUANDO A INTERFACE(COMPONENTE) ESTIVER PRONTO:

```ts
  const id = localStorage.getItem('idUsuario')


 useEffect(() => {
    async function relatorio() {
      const geral = (await fetch(bikeEndpoint + `/geral?idUser=${id}`)).json()
      return geral
    }

    relatorio().then(({cod_bike,description,media,status}) => {
      // PASSAR VALORES PARA AS VARIÁVEIS AQUI:
      // EXEMPLO:
      // setCod_bike(cod_bike)
      // setStatus(status)
      // setDescription(description)
      // setMedia(media)
    })

  }, [id])
```

**Comment by itsmorais** [comment]
![image](https://github.com/DevsDomain/Bike4you/assets/53665466/6e141421-9556-4463-afd2-72d96a77cb45)

Teste feito
