### ISSUE TITLE
Documentação do banco de Dados

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#11]
Documente a estrutura do banco de dados, os esquemas das tabelas, a API e os procedimentos de manutenção para facilitar futuras atualizações e manutenções.

**Comment by Jummanso** [comment]
Versão 1 da modelagem de banco de Dados

[Mapa Banco V.1.pdf](https://github.com/Dev-s-Domain/DomainBicicletas/files/12530436/Mapa.Banco.V.1.pdf)

**Comment by Jummanso** [comment]
Compactação da primeira versão da modelagem com acréscimo de informações consideradas relevantes. 



![Image](https://github.com/Dev-s-Domain/DomainBicicletas/assets/126696706/a5c9af30-7205-49ae-bb90-17f55ad64557)

**Comment by Jummanso** [comment]
Criação tabelas TypeORM



![Image](https://github.com/Dev-s-Domain/Bike4you/assets/126696706/57ad58e4-d8dc-4493-a35e-b72b03160cbb)

**Comment by Jummanso** [comment]
Atualização modelagem:



![Image](https://github.com/Dev-s-Domain/Bike4you/assets/126696706/2d800e7d-7206-4e1d-9ef3-f98debe43f4f)

**Comment by itsmorais** [comment]
Ok
