### ISSUE TITLE
Padronizar Estilo dos Componentes da Pagina de gerenciamento

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#111]
Padronizar CSS

**Comment by Jummanso** [comment]
feita a padronização:



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/16f133f6-9565-4afa-a3b3-496b24868757)

**Comment by Jummanso** [comment]
Estilo padronizado:



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/c6be8625-d50c-4127-8882-8162f03a60ea)


![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/221d1bd6-a92d-4b49-85aa-45e49aa53d4a)



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/5325e67e-3932-44f2-8e88-25e61a800d06)
