### ISSUE TITLE
Adicionar lista, pilha ou fila no projeto para avaliação na matéria de Estrutura de Dados

### ISSUE THREAD

**Issue by Jummanso** [DevsDomain/Bike4you#121]

**Comment by Jummanso** [comment]
@itsmorais por favor verificar se consegui fazer a inclusão de forma correta. Está na branche abaixo:

https://github.com/DevsDomain/Bike4you/tree/Inclusao_Lista

**Comment by itsmorais** [comment]
Testado e aprovado!
