### ISSUE TITLE
Gerar Script para popular banco de dados

### ISSUE THREAD

**Issue by itsmorais** [DevsDomain/Bike4you#129]
- Criar 4 usuários
- 1 usuário não terá bike cadastrada
- 3 usuários terão 3 bikes cadastradas( ou seja 9 bikes cadastradas no total)
- Gerar 3 avaliações entre os clientes de sua escolha (deixar ao menos 3 bikes com avaliações)

exemplo: Quando 1 bike tem avaliação o componente de estrela fica automaticamente preenchido de acordo com a média das notas

![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/eb193a34-4762-4a6c-a7f4-49136e521c84)

exemplo de avaliação preenchida no banco (tabela rents)

![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/47a453ba-b02c-451f-af12-0dea332e61ab)

**Comment by Jummanso** [comment]
**4 usuarios criados, 3 usuários com 3 bicicletas cadastras (total de 9 bicicletas cadastradas)  e um sem nenhuma conforme solcicitação.** 

**Avaliação conforme abaixo:**

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/96c2ee5c-33bf-4b05-83d1-a0440085d77c)

**Card já alimentou avaliação:**

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/7d5fac36-6888-4d60-9337-315229805fcf)

**Foi modificado o layout das bikes cadastradas para ficar mais agradável ao usuário:**

**Tela sem bike cadastrada:**

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/bb35ff00-992a-4cb8-8f82-72c0035b0104)

**Tela com bike cadastrada:**

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/88b8cf01-ea6b-49d5-b18c-5c5af498b07e)

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/e2e333ca-7728-4e88-8248-659d26420c6e)

Sxript anexado em txt, pois não foi aceito em .sql

[script_insercao_completo.txt](https://github.com/DevsDomain/Bike4you/files/13395014/script_insercao_completo.txt)

**Comment by itsmorais** [comment]
A coluna de status na modificação de layout está cortando a parte escrita do status 

branch: Alteracao_Layout_Geral
![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/e47e580b-02c7-44cf-976e-6fdc47582f52)

branch: Main
![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/954bfb3e-b6af-4417-8ed3-568f1bc44ffa)

**Comment by Jummanso** [comment]
Problema arrumado:

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/3e5e5076-9a17-451e-a4a2-5012d3242d5f)

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/ee7a8296-9d8f-4f18-867f-40e6a272085d)

**Comment by itsmorais** [comment]
Resolvido
