### ISSUE TITLE
Wireframe HomePage - Figma

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#13]
Desenvolver um protótipo da página de visualização de bicicleta.

**Comment by abnercosta97** [comment]
Inicio do Wireframe, criação do prototipo da página Home no Figma. [Link](https://www.figma.com/file/ioPTAYSQ74rjAjUc235cKC/RentByk--Bike-Rental-App-Landing-page-(Community)?type=design&node-id=0%3A1&mode=design&t=CU83KAeKrck9xJmV-1)

**Comment by fnddavi** [comment]
Inicio do Wireframe, criação do protótipo da página Home no Figma.

**Comment by abnercosta97** [comment]
Link do prototipo [home ](https://www.figma.com/file/ioPTAYSQ74rjAjUc235cKC/RentByk--Bike-Rental-App-Landing-page-(Community)?type=design&node-id=0%3A1&mode=design&t=HFLT3vupURN4tNBP-1)

**Comment by itsmorais** [comment]
Aguardando revisão dos demais integrantes: 
@Jummanso @Lemos05 @Claudia-Nunes

**Comment by Claudia-Nunes** [comment]
Eu Achei super legal a pagina, conforme conversei com o Abner ontem, eu apenas acrescentaria o Footer, que inclisive é a minha tarefa dessa semana com React.
@itsmorais  @abnercosta97

**Comment by itsmorais** [comment]
Ok!

**Comment by Claudia-Nunes** [comment]
https://www.figma.com/files/team/1283975866139292129

**Comment by Claudia-Nunes** [comment]
Concluído as páginas de protótipo com interação das telas!
 @itsmorais @Jummanso @abnercosta97
