### ISSUE TITLE
Criar Diagrama de Classe Modelo UML

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#20]
Documente os modelos UML de forma clara e completa para que possam ser usados como referência durante o desenvolvimento.

**Comment by itsmorais** [comment]
**Iniciado diagrama da Classe Usuario**

https://www.figma.com/file/UJVBJKG1mP3NjbvlP990Av/UML-API2-(Copy)?type=whiteboard&node-id=0-1&t=ha50q81hFWLMvFHM-0

**Comment by itsmorais** [comment]
Criação do diagrama de classes UML para as classes:
- Categoria
- Usuario
- Bike
- Contrato
- Photo
- Brand
- Address
https://www.figma.com/file/UJVBJKG1mP3NjbvlP990Av/UML-API2-(Copy)?type=whiteboard&node-id=0%3A1&t=MgWfWe9WRwoO96Ec-1

**Comment by itsmorais** [comment]
ok
