### ISSUE TITLE
Desenvolver página para cadastro de Bikes - REACT

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#22]
- [x] Desenvolver a interface em React
- [x] Enviar dados para o backend 
- [ ] Exibir listagem das bikes cadastradas

**Comment by Claudia-Nunes** [comment]
@abnercosta97  e @BiaMontanini ,
esta tarefa precisará ser encerrada até amanha, mesmo que não tenha sido finalizada, e poderá ser reaberta na Sprint#2

**Comment by itsmorais** [comment]
Pull request aberto: #66 
Aguardando revisão e aprovação para merge na branch MAIN

**Comment by itsmorais** [comment]
Validado por @abnercosta97
