### ISSUE TITLE
Script de Dados Cadastraveis

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#28]
- [ ] Criar tabela em Excel e completar com dados fictícios.
- [ ] **Não precisa inserir dados na tabela users e rent**

**Comment by Jummanso** [comment]
Criada tabela em Excel para ser usada como base dos modelos a serem inseridos. 
Campos em cinza não precisam ser completados e campo em rosa é o que não tinha o dado na página de venda.

@Lemos05 por favor dar continuidade com os demais cadastros fictícios.

[Cadastros.xlsx](https://github.com/DevsDomain/Bike4you/files/12592169/Cadastros.xlsx)

**Comment by Lemos05** [comment]
Atualização de informações das bikes.

**Comment by Lemos05** [comment]
Dados cadastráveis finalizado.

https://fatecspgov-my.sharepoint.com/personal/nicolas_lemos_fatec_sp_gov_br/Documents/Arquivos%20de%20Chat%20do%20Microsoft%20Teams/Cadastros%20(3).xlsx?web=1

**Comment by itsmorais** [comment]
Necessário liberar acesso ao link


![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/ec2aa805-a411-494c-b489-d47a771a56fb)

**Comment by itsmorais** [comment]
@abnercosta97  Podemos utilizar esses dados para cadastrar as bikes
