### ISSUE TITLE
Desenvolver página de Login e Cadastro de usuário - REACT

### ISSUE THREAD

**Issue by itsmorais** [DevsDomain/Bike4you#42]
Desenvolver interface em react para cadastrar usuários -> Salvar no Banco de dados
Desenvolver interface em react para Login usuários

**Comment by itsmorais** [comment]
#41 Aguardando teste e aprovação de PR 
@Jummanso

**Comment by Jummanso** [comment]
Teste feito e tudo funcionando.



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/6bbb138e-acaa-4332-9345-10138e3c7d8f)



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/5750e614-2e6b-465f-b300-918328d9f055)
