### ISSUE TITLE
Componente -> Editar Dados Do Usuário

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#51]
Editar Dados Do Usuário,  ele já estando autenticado

**Comment by itsmorais** [comment]
![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/12597530-fc01-4fb4-b11b-f35d2fa8aa0a)

**Comment by Jummanso** [comment]
Tela refeita com habilitação do botão editar:

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/cda47292-7117-4fa2-8652-3e22d954312b)

Efetuado teste do botão e confirmada a alteração dos dados no banco.

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/49eaf997-c432-497e-84b5-3ef99a481f67)

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/785ed6c5-f141-45ea-8fac-4789513b3ac1)

**Comment by Jummanso** [comment]
Alterado conteúdos de alguns campos para tela ficar mais intuitiva:

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/779228eb-3bb4-498b-8216-d04856fb328e)

@abnercosta97 já foi commitado essa versão final e já coloquei o encaminhamento para a sua página de cadastrar bike através do seu arquivo que peguei ontem após seu último commit.
