### ISSUE TITLE
Criar componente - Footer

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#56]
Criar componente "Footer", conforme protótipo figma, porém deverá ser melhorado e ajustado ao padrão de mercado.

EXEMPLO:

![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/91ee481f-7672-4fa1-b70f-1a49be9ae207)

**Comment by Lemos05** [comment]
Footer criado, porém não sei aonde colocar pois meu computador abre apenas o index.html no google. só que essa pasta não tem nenhum conteúdo.

**Comment by Claudia-Nunes** [comment]
Tarefa Cancelada

**Comment by Lemos05** [comment]
Footer já criado, falta só arrumar o css.
