### ISSUE TITLE
Desenvolver tela de gerênciamento

### ISSUE THREAD

**Issue by itsmorais** [DevsDomain/Bike4you#61]
Desenvolver tela responsável por:
editar dados das bikes -> Incluindo status(Disponível, Alugada)
editar dados do usuário

![Image](https://github.com/DevsDomain/Bike4you/assets/53665466/38bd3a21-dc94-4b51-8a39-7bbfe98d464b)

**Comment by Jummanso** [comment]
Início estudo react.

**Comment by Jummanso** [comment]
Iniciando estilização da tela:



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/17ac121f-a4aa-401d-859d-fd7855b49034)

**Comment by Jummanso** [comment]
@itsmorais sobre esse comentário:

editar dados das bikes -> Incluindo status(Disponível, Alugada)

Preciso criar esses campos na tela acima?

**Comment by itsmorais** [comment]
Esses campos serão criados pelo @abnercosta97

**Comment by Jummanso** [comment]
Continuidade da estilização:



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/8eb858c6-b0d3-445a-82ec-beaa1ab81f5f)

**Comment by Jummanso** [comment]
Alterada cor botão e incluso sombreamento:



![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/d7425852-cd6b-4745-8c6b-6f9c10e00ac8)

**Comment by Jummanso** [comment]
@abnercosta97 e @itsmorais Edição feita conforme solicitação para conferência na branche.

![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/44cb2809-43d1-41fa-92ee-45708aa06e45)

**Comment by itsmorais** [comment]
@Jummanso seria interessante alterar o estilo do input cidade e bairro, uma vez que são Campos desabilitados.
Pra dar uma informação visual ao usuário. Assim fica mais claro o que o usuário pode ou não alterar

**Comment by itsmorais** [comment]
No demais, tá excelente! 👏🏼

**Comment by Jummanso** [comment]
@itsmorais Alterações feitas conforme sua solicitação:


![Image](https://github.com/DevsDomain/Bike4you/assets/126696706/9aee6c69-bcd0-45b3-b35f-bbbaf0a3602d)
