### ISSUE TITLE
Desenvolver backend Express

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#7]
Desenvolva uma API que permita o cadastro, atualização, leitura e exclusão das Bikes conectado ao Banco de dados.
Utilize TypeORM 
Utilize o modelo MVC para a criação de classes e funções

**Comment by itsmorais** [comment]
Aguardando aprovação de Pull request no github.
Link https://github.com/Dev-s-Domain/Bike4you/pull/40
@abnercosta97  @Jummanso 



![Image](https://github.com/Dev-s-Domain/Bike4you/assets/53665466/3f016e8d-802b-4609-800c-16d99a1ed138)

**Comment by itsmorais** [comment]
Ok
