### ISSUE TITLE
Estudo de React

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#9]
Aprender a utilizar a tecnologia React e as seguintes bibliotecas:
axios, useState, useEffect , Componentes

**Comment by Jummanso** [comment]
13-09 Início estudo curso react:

https://www.youtube.com/watch?v=FXqX7oof0I4&list=PLnDvRpP8BneyVA0SZ2okm-QBojomniQVO

**Comment by fnddavi** [comment]
Material sendo visto:

**Comment by Claudia-Nunes** [comment]
Estudo De React da Sprint 1, concluída com sucesso!
