### ISSUE TITLE
Desenvolver página de Detalhe da bike

### ISSUE THREAD

**Issue by Claudia-Nunes** [DevsDomain/Bike4you#99]
![Image](https://github.com/DevsDomain/Bike4you/assets/104475381/55430d09-2dea-4ca2-a2a1-742eb2574e2e)

**Comment by Claudia-Nunes** [comment]
@abnercosta97 Conectar os componentes:

**Comment by abnercosta97** [comment]
Finalizada, nã;o está na main, esperando card finalizar
